version: '3'

services:
  db:
    image: mariadb
    #image: jsurf/rpi-mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: [mariadb_root_password]
      MYSQL_DATABASE: [mariadb_db_name]
      MYSQL_USER: [mariadb_user_name]
      MYSQL_PASSWORD: [mariadb_user_password]
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
      - '80:80'
    depends_on:
      - db
    privileged: true